# SITE CONFIGURATION
title: 기술 저장소 # your site title
author: 강윤석 # You :P
description: > # Meta description of Homepage
  .NET 및 여러 개발 관련 경험 및 지식을 생각나는 대로 업로드 하는 블로그.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kayuse88.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: 강윤석
  links:
    - https://github.com/kayuse88

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Categories', link: '/categories'}
#  - {name: 'About', link: '/about'}
#  - {name: 'Contact', link: '/contact'}

tagline: >
  개발 지식을 커밋하는 곳

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: kayuse@icloud.com # email for form submission

# twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  kayuse88 # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: yunseoks-blog # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag